In [1]:
import numpy as np

In [12]:
arry = np.array([1, 2, 3, 4, 5])
print(arry)

[1 2 3 4 5]


In [11]:
arry2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arry2)
print(arry2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
arry3 = np.array([[1 , 2, 3,] , [4, 5, 6], [7, 8, 9]])
print(arry3)
print(arry3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [9]:
arry4 = np.array([[[1 , 2, 3,] , [4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arry4)

print(arry4.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3


In [16]:
arry5 = np.array([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]]])
print(arry5)
print(arry5.ndim)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]]
4


In [18]:
import numpy as np
arr = np.array(arry5)
print(arr.dtype)

int64


In [22]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[1, 2])  # Access element at row 1, column 2 (6)

# Using a single tuple of indices
indices = (1, 2)
print(arr_2d[indices])  # Access the same element (6)

print(arr_2d[ :, 1]) 
print(arr_2d[1, :])

6
6
[2 5]
[4 5 6]
